[workspace]
members = ["crates/requirement_checker_interface", "crates/disclosure_interface", "crates/zk_certificate_content", "crates/zk_certificate", "crates/use_case_example", "crates/age_check_requirement", "crates/basic_disclosure", "crates/shamir_disclosure"]
