[package]
name = "ecdsa_k_eth_signer_account"
authors = [""]
compiler_version = ">=1.0.0"
type = "contract"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v3.0.0-devnet.20251212", directory = "noir-projects/aztec-nr/aztec" }
keccak256 = { git = "https://github.com/noir-lang/keccak256", tag = "v0.1.0" }
