[package]
name = "use_case_example"
type = "contract"
authors = [ "Galactica Network" ]
compiler_version = ">=0.18.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-nr/", tag = "v3.0.0-devnet.20251212", directory = "aztec" }
zk_certificate = { path = "../zk_certificate" }
age_check_requirement = { path = "../age_check_requirement" }
requirement_checker_interface = { path = "../requirement_checker_interface" }
