[package]
name = "zk_certificate"
type = "contract"
authors = [ "Galactica Network" ]
compiler_version = ">=1.0.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v4.0.0-devnet.2-patch.0", directory = "noir-projects/aztec-nr/aztec" }
age_check_requirement = { path = "../age_check_requirement" }
basic_disclosure = { path = "../basic_disclosure" }
disclosure_interface = { path = "../disclosure_interface" }
requirement_checker_interface = { path = "../requirement_checker_interface" }
shamir_disclosure = { path = "../shamir_disclosure" }
zk_certificate_content = { path = "../zk_certificate_content" }
